export interface User {
  thoi_gian_get_data: string
  ma_sv: string
  ten_day_du: string
  gioi_tinh: string
  ngay_sinh: string
  dan_toc: string
  ton_giao: string
  dien_thoai: string
  email: string
  dien_thoai2: string
  email2: string
  doi_mat_khau: boolean
  lop: string
  khu_vuc: string
  doi_tuong_uu_tien: string
  khoi: string
  nganh: string
  chuyen_nganh: string
  id_chuyen_nganh: string
  khoa: string
  bac_he_dao_tao: string
  nien_khoa: string
  ma_cvht: string
  ho_ten_cvht: string
  email_cvht: string
  dien_thoai_cvht: string
  ma_cvht_ng2: string
  ho_ten_cvht_ng2: string
  email_cvht_ng2: string
  dien_thoai_cvht_ng2: string
  ma_truong: string
  ten_truong: string
  id_dia_phuong: string
  id_khoa: string
  id_sinh_vien: string
  id_lop: string
  id_khoi: string
  id_bac_he_nganh: string
  id_bac_he: string
  id_he: string
  id_quy_che: string
  id_quy_che_P: string
  id_hoc_che: string
  id_don_vi_phan_cap: string
  id_co_so_lop: string
  nhhk_vao: number
  nhhk_ra: number
  id_lop2: string
  id_khoi2: string
  id_bac_he_nganh2: string
  is_master_pass: boolean
  is_cvht_dang_nhap: boolean
  is_phu_huynh_dang_nhap: boolean
  int_hien_dien_sv: number
  hien_dien_sv: string
  int_hien_dien_dkmh: number
  ds_menu_cam_xem: any[]
  str_hoan_thanh_dgrl: string
  url_netweb: string
}
